#h2 connection url 옵션에 대한 정보는 : https://www.h2database.com/html/features.html#database_url 참고
#DB_CLOSE_DELAY=-1 -> db 컨텐츠 유지를 위한 옵션
#jdbc:h2:tcp://localhost:9123/mem:elbath 으로 접속
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:elbath;DB_CLOSE_DELAY=-1
    username: elbath
    password: elbath

logging.level.org.springframework.batch: DEBUG

#program arg 로 받는 파라미터 중 --job.name=Job이름 에 해당 하는 것만 실행, 값이 없으면 아무것도 실행 안함
spring.batch.job.names: ${job.name:NONE}